# BAG OF WORDS 

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
import pandas as pd

In [37]:
df = pd.read_csv("X:\\EEM Dosyalar\\Yazan Zeka 4e Academy\\NLP Dogal Dil\\Natural-Language-Processing/data/nlp_proje_metin_siniflandirma.csv", 
                index_col = 0)
df.head()

Text  Label
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1
1               hayat paylaşınca güzel...türkcell...      1
2                         superonline varya daha iyi      1
3                hahaha kanka turkcell bu 4 ceker :d      1
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1

In [38]:
import on_islem

In [39]:
df["Text_2"] = df["Text"].apply(on_islem.pre_processing)
df["Text_2"] = df["Text_2"].apply(on_islem.remove_space)
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...  
1                     [hayat, paylaş, güzeltürkcell]  
2                             [superonl, varya, dah]  
3                    [hahah, kanka, turkcell, ceker]  
4          [turkcell, tl, hedi, et, ba, güzel, olur]

In [40]:
#bos liste kontrolu

df[df["Text_2"].str[0].isnull()]

Text  Label Text_2
1608                    :s      3     []
2200  #turkcellesavasimvar      2     []

In [41]:
df_index = df[df["Text_2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()
del df["index"]

df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Label, Text_2]
Index: []

In [42]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...  
1                     [hayat, paylaş, güzeltürkcell]  
2                             [superonl, varya, dah]  
3                    [hahah, kanka, turkcell, ceker]  
4          [turkcell, tl, hedi, et, ba, güzel, olur]

In [43]:
df["Text_2"]

0       [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...
1                          [hayat, paylaş, güzeltürkcell]
2                                  [superonl, varya, dah]
3                         [hahah, kanka, turkcell, ceker]
4               [turkcell, tl, hedi, et, ba, güzel, olur]
                              ...                        
2993                         [gördük, adi, şerefsiz, kur]
2994                            [se, ben, boykot, edicem]
2995    [diğer, hat, çekmedik, yer, çeke, hat, çektik,...
2996    [sanir, g, baglanti, sor, var, surekli, edge, ...
2997    [besiktas, metropol, sube, olduk, ukel, turkce...
Name: Text_2, Length: 2998, dtype: object

In [44]:
df["Text_3"] = [' '.join(w for w in item) for item in df["Text_2"]]
df

Text  Label  \
0     turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1                  hayat paylaşınca güzel...türkcell...      1   
2                            superonline varya daha iyi      1   
3                   hahaha kanka turkcell bu 4 ceker :d      1   
4       turkcell 3 tl hediye etse bana ne güzel olur =)      1   
...                                                 ...    ...   
2993                gördüğüm en adi şerefsiz kurumsunuz      2   
2994               #turkcell seni de ben boykot edicem.      2   
2995  diğer hatların çekmediği yerde çeken her hattı...      2   
2996  sanirim 3g baglanti sorunu var, surekli edge o...      2   
2997  besiktas metropol subeniz oldukca ukela bu tur...      2   

                                                 Text_2  \
0     [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                        [hayat, paylaş, güzeltürkcell]   
2                                [superonl, varya, dah]   
3                       [hahah, kanka, turkcell, ceker]   
4             [turkcell, tl, hedi, et, ba, güzel, olur]   
...                                                 ...   
2993                       [gördük, adi, şerefsiz, kur]   
2994                          [se, ben, boykot, edicem]   
2995  [diğer, hat, çekmedik, yer, çeke, hat, çektik,...   
2996  [sanir, g, baglanti, sor, var, surekli, edge, ...   
2997  [besiktas, metropol, sube, olduk, ukel, turkce...   

                                                 Text_3  
0     turkcellmüzik biraz dah geliş fizy yi tamame b...  
1                            hayat paylaş güzeltürkcell  
2                                    superonl varya dah  
3                            hahah kanka turkcell ceker  
4                     turkcell tl hedi et ba güzel olur  
...                                                 ...  
2993                            gördük adi şerefsiz kur  
2994                               se ben boykot edicem  
2995  diğer hat çekmedik yer çeke hat çektik yer çek...  
2996  sanir g baglanti sor var surekli edge oluyor i...  
2997  besiktas metropol sube olduk ukel turkcele hic...  

[2998 rows x 4 columns]

In [11]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df["Text_3"].tolist())
x

<2998x9036 sparse matrix of type '<class 'numpy.int64'>'
	with 28456 stored elements in Compressed Sparse Row format>

In [12]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
x[0]

<1x9036 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [14]:
df["Text_4"] = x.toarray().tolist()
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3  \
0  turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                         hayat paylaş güzeltürkcell   
2                                 superonl varya dah   
3                         hahah kanka turkcell ceker   
4                  turkcell tl hedi et ba güzel olur   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

# TF-IDF

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df["Text_3"].tolist())

In [16]:
print(x.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
set(x.toarray()[0])

{0.0,
 0.1992790368712647,
 0.3018250542765058,
 0.3151401837148609,
 0.352673425541056,
 0.36598855497941113,
 0.38475517589250874}

In [18]:
df["Text_5"] = x.toarray().tolist()
df

Text  Label  \
0     turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1                  hayat paylaşınca güzel...türkcell...      1   
2                            superonline varya daha iyi      1   
3                   hahaha kanka turkcell bu 4 ceker :d      1   
4       turkcell 3 tl hediye etse bana ne güzel olur =)      1   
...                                                 ...    ...   
2993                gördüğüm en adi şerefsiz kurumsunuz      2   
2994               #turkcell seni de ben boykot edicem.      2   
2995  diğer hatların çekmediği yerde çeken her hattı...      2   
2996  sanirim 3g baglanti sorunu var, surekli edge o...      2   
2997  besiktas metropol subeniz oldukca ukela bu tur...      2   

                                                 Text_2  \
0     [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                        [hayat, paylaş, güzeltürkcell]   
2                                [superonl, varya, dah]   
3                       [hahah, kanka, turkcell, ceker]   
4             [turkcell, tl, hedi, et, ba, güzel, olur]   
...                                                 ...   
2993                       [gördük, adi, şerefsiz, kur]   
2994                          [se, ben, boykot, edicem]   
2995  [diğer, hat, çekmedik, yer, çeke, hat, çektik,...   
2996  [sanir, g, baglanti, sor, var, surekli, edge, ...   
2997  [besiktas, metropol, sube, olduk, ukel, turkce...   

                                                 Text_3  \
0     turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                            hayat paylaş güzeltürkcell   
2                                    superonl varya dah   
3                            hahah kanka turkcell ceker   
4                     turkcell tl hedi et ba güzel olur   
...                                                 ...   
2993                            gördük adi şerefsiz kur   
2994                               se ben boykot edicem   
2995  diğer hat çekmedik yer çeke hat çektik yer çek...   
2996  sanir g baglanti sor var surekli edge oluyor i...   
2997  besiktas metropol sube olduk ukel turkcele hic...   

                                                 Text_4  \
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                 ...   
2993  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2994  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2996  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2997  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                 Text_5  
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
...                                                 ...  
2993  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2994  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2997  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[2998 rows x 6 columns]

In [19]:
len(x.toarray()[0])

9036

# Word2Vec

In [20]:
from gensim.models import Word2Vec

In [21]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3  \
0  turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                         hayat paylaş güzeltürkcell   
2                                 superonl varya dah   
3                         hahah kanka turkcell ceker   
4                  turkcell tl hedi et ba güzel olur   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [22]:
model = Word2Vec(sentences = df["Text_2"].tolist(), vector_size = 100, 
                 window = 5, min_count = 1)
model.save("X:\\EEM Dosyalar\\Yazan Zeka 4e Academy\\NLP Dogal Dil\\Natural-Language-Processing/data/word2vec.model")

In [23]:
print(model)

Word2Vec<vocab=9050, vector_size=100, alpha=0.025>


In [24]:
words = list(model.wv.index_to_key)
words[0:6]

['turkcell', 'bir', 'mesaj', 'be', 'bi', 'am']

In [25]:
len(words)

9050

In [26]:
df

Text  Label  \
0     turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1                  hayat paylaşınca güzel...türkcell...      1   
2                            superonline varya daha iyi      1   
3                   hahaha kanka turkcell bu 4 ceker :d      1   
4       turkcell 3 tl hediye etse bana ne güzel olur =)      1   
...                                                 ...    ...   
2993                gördüğüm en adi şerefsiz kurumsunuz      2   
2994               #turkcell seni de ben boykot edicem.      2   
2995  diğer hatların çekmediği yerde çeken her hattı...      2   
2996  sanirim 3g baglanti sorunu var, surekli edge o...      2   
2997  besiktas metropol subeniz oldukca ukela bu tur...      2   

                                                 Text_2  \
0     [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                        [hayat, paylaş, güzeltürkcell]   
2                                [superonl, varya, dah]   
3                       [hahah, kanka, turkcell, ceker]   
4             [turkcell, tl, hedi, et, ba, güzel, olur]   
...                                                 ...   
2993                       [gördük, adi, şerefsiz, kur]   
2994                          [se, ben, boykot, edicem]   
2995  [diğer, hat, çekmedik, yer, çeke, hat, çektik,...   
2996  [sanir, g, baglanti, sor, var, surekli, edge, ...   
2997  [besiktas, metropol, sube, olduk, ukel, turkce...   

                                                 Text_3  \
0     turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                            hayat paylaş güzeltürkcell   
2                                    superonl varya dah   
3                            hahah kanka turkcell ceker   
4                     turkcell tl hedi et ba güzel olur   
...                                                 ...   
2993                            gördük adi şerefsiz kur   
2994                               se ben boykot edicem   
2995  diğer hat çekmedik yer çeke hat çektik yer çek...   
2996  sanir g baglanti sor var surekli edge oluyor i...   
2997  besiktas metropol sube olduk ukel turkcele hic...   

                                                 Text_4  \
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                 ...   
2993  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2994  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2996  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2997  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                 Text_5  
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
...                                                 ...  
2993  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2994  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2997  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[2998 rows x 6 columns]

In [27]:
model.wv.key_to_index["payla"]

331

In [28]:
model.wv[3]

array([-0.03635924,  0.10714187,  0.05793305,  0.02519611, -0.03166847,
       -0.21174946,  0.03831191,  0.23795097, -0.05968326, -0.10205091,
       -0.02876518, -0.15673912, -0.03651063,  0.08316707,  0.03260769,
       -0.11879466,  0.07153495, -0.15489992,  0.01848449, -0.259506  ,
        0.10958473,  0.05367033,  0.13348928, -0.06443512, -0.01814819,
       -0.01779379, -0.11275283, -0.08519314, -0.13234627, -0.02669359,
        0.08371809,  0.02681685,  0.04714718, -0.13622567, -0.02254371,
        0.10361581,  0.04948644, -0.06437625, -0.06412692, -0.21251723,
        0.06091214, -0.06706022, -0.02320436,  0.01482673,  0.09635039,
       -0.06319393, -0.1618164 ,  0.01213411,  0.06611473,  0.06871709,
        0.05872814, -0.06484662, -0.07822347, -0.03942883, -0.04291139,
        0.03519132,  0.12254108,  0.0156823 , -0.11406737,  0.03325971,
        0.00344243,  0.01587958, -0.00091809,  0.01505996, -0.08744913,
        0.07786619, -0.01070617,  0.10164236, -0.14833552,  0.08

In [29]:
model.wv.get_vector("turkcel")

array([-0.02039406,  0.05128062,  0.0422569 ,  0.02580148, -0.01375897,
       -0.13330902,  0.0264313 ,  0.14357224, -0.03399016, -0.06426938,
       -0.02297765, -0.1041483 , -0.03417458,  0.05534774,  0.02434624,
       -0.06340067,  0.03059931, -0.08683608,  0.0133014 , -0.14989232,
        0.05586865,  0.04308579,  0.06724907, -0.05223982, -0.00278531,
       -0.01259298, -0.0801934 , -0.05415634, -0.08102067, -0.02316364,
        0.05489558,  0.02169471,  0.04108655, -0.07255724, -0.0234697 ,
        0.06127411,  0.02929673, -0.02901223, -0.02679597, -0.1388492 ,
        0.03971243, -0.04183517, -0.01706109,  0.00432043,  0.05419809,
       -0.03442832, -0.1087321 ,  0.01800495,  0.04431912,  0.043432  ,
        0.02828335, -0.03853303, -0.03517025, -0.01378328, -0.02801653,
        0.02893029,  0.07183196, -0.00388836, -0.06343858,  0.02816622,
        0.00562048,  0.01420299, -0.01248538,  0.00373035, -0.05761067,
        0.0461945 , -0.006873  ,  0.05526517, -0.09583831,  0.06

In [30]:
def word2vec(value):
    model = Word2Vec.load("X:\\EEM Dosyalar\\Yazan Zeka 4e Academy\\NLP Dogal Dil\\Natural-Language-Processing/data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)

    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)

    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [31]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3  \
0  turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                         hayat paylaş güzeltürkcell   
2                                 superonl varya dah   
3                         hahah kanka turkcell ceker   
4                  turkcell tl hedi et ba güzel olur   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [32]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [33]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3  \
0  turkcellmüzik biraz dah geliş fizy yi tamame b...   
1                         hayat paylaş güzeltürkcell   
2                                 superonl varya dah   
3                         hahah kanka turkcell ceker   
4                  turkcell tl hedi et ba güzel olur   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.005073799751698971, 0.013080107979476452, ...  
1  [-0.02576817385852337, 0.04763680323958397, 0....  
2  [-0.017672989517450333, 0.052493344992399216, ...  
3  [-0.013882005587220192, 0.05975135788321495, 0...  
4  [-0.016026871278882027, 0.07796841114759445, 0...

In [45]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3  
0  turkcellmüzik biraz dah geliş fizy yi tamame b...  
1                         hayat paylaş güzeltürkcell  
2                                 superonl varya dah  
3                         hahah kanka turkcell ceker  
4                  turkcell tl hedi et ba güzel olur

In [46]:
df["bow"] = on_islem.bag_of_words(df["Text_3"])
df["tfidf"] = on_islem.tfidf(df["Text_3"])
df["word2vec"] = df["Text_2"].apply(on_islem.word2vec)

In [47]:
df.head()

Text  Label  \
0  turkcellmüzik biraz daha gelişsin fizy yi tama...      1   
1               hayat paylaşınca güzel...türkcell...      1   
2                         superonline varya daha iyi      1   
3                hahaha kanka turkcell bu 4 ceker :d      1   
4    turkcell 3 tl hediye etse bana ne güzel olur =)      1   

                                              Text_2  \
0  [turkcellmüzik, biraz, dah, geliş, fizy, yi, t...   
1                     [hayat, paylaş, güzeltürkcell]   
2                             [superonl, varya, dah]   
3                    [hahah, kanka, turkcell, ceker]   
4          [turkcell, tl, hedi, et, ba, güzel, olur]   

                                              Text_3   bow  \
0  turkcellmüzik biraz dah geliş fizy yi tamame b...  None   
1                         hayat paylaş güzeltürkcell  None   
2                                 superonl varya dah  None   
3                         hahah kanka turkcell ceker  None   
4                  turkcell tl hedi et ba güzel olur  None   

                                               tfidf  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.005073799751698971, 0.013080107979476452, ...  
1  [-0.02576817385852337, 0.04763680323958397, 0....  
2  [-0.017672989517450333, 0.052493344992399216, ...  
3  [-0.013882005587220192, 0.05975135788321495, 0...  
4  [-0.016026871278882027, 0.07796841114759445, 0...